### ISSUE TITLE
Quick Q: Does DenSPI depend on CoreNLP? 

### ISSUE THREAD

**Issue by waalge** [uwnlp/denspi#11]
Its in the installer [here](https://github.com/uwnlp/denspi/blob/f540b6a547f012823fc6c2bb10077df6bccc13a6/install.sh#L16)

but its commented out in the [Dockerfile](https://github.com/uwnlp/denspi/blob/ad7b8c38006530d1b1ad3bde05f622a4518b54ad/open/Dockerfile#L23). 

I haven't seen any other reference to it.

**Comment by jhyuklee** [comment]
Hi @waalge , the DrQA installation requires the CoreNLP installation. You might not need that if you don't want to use the CoreNLP tokenizer in DrQA.

**Comment by waalge** [comment]
Thanks for your reply, 
Ok. Yeah, I understood that its interchangeable with spacy. 
Although its not immediate whether this gives comparable results.
