### ISSUE TITLE
How to handle short sentences/contexts

### ISSUE THREAD

**Issue by RamanRajarathinam** [uwnlp/denspi#13]
Hi @seominjoon  @jhyuklee 
- The default model performs well for SQUAD_v1.1 dataset (where context length is ~700 chars)
But It fails to perform, when I try to index my custom data which has small paragraph/contexts (length ~100-150 characters).
    - The problem is, irrespective of the query, the same result (wrong) is being returned as the output
    - Most the time, the result is just single random character like **?**  **.** (end of the context)
    - I have debugged into this and realized that the problem stays in **start vectors** which we generate from model output

**Ques:**
1. May I know why this scenario occurs?
2. What is the solution?
 
**Setting:**
All the results are obtained using the commands mentioned in README.

**Comment by jhyuklee** [comment]
Reference: https://github.com/uwnlp/denspi/issues/2
