### ISSUE TITLE
Handle short sentences 

### ISSUE THREAD

**Issue by seominjoon** [uwnlp/denspi#2]

**Comment by RamanRajarathinam** [comment]
Hi @jhyuklee May I know what do you mean by concatenation? Is it a text concatenation or vector concatenation?

Please refer https://github.com/uwnlp/denspi/issues/13 for more details

**Comment by jhyuklee** [comment]
Hi @RamanRajarathinam. We concatenated short sentences into a single paragraph (an input to BERT), then performed the indexing. This resolved the short sentence issues.

**Comment by RamanRajarathinam** [comment]
Oh okay.. But may I know why model is not performing as expected when the input text is short?

**Comment by jhyuklee** [comment]
That's because the model was trained on SQuAD which usually contains a passage longer than a sentence.

**Comment by RamanRajarathinam** [comment]
So the only solution is to concatenate different texts? or Is there any other way to solve this?

**Comment by RamanRajarathinam** [comment]
Can you also please comment on this issue https://github.com/uwnlp/denspi/issues/9 ?

**Comment by jhyuklee** [comment]
So the only solution is to concatenate different texts? or Is there any other way to solve this?
=> For now, yes but I guess there can be plenty of other solutions that can de-bias the length bias like augmenting short passage QA training pairs.
