### ISSUE TITLE
how to convert each float32 value to int8?

### ISSUE THREAD

**Issue by Jasperty** [uwnlp/denspi#4]
how to convert each float32 value to int8? where is the code about this?

**Comment by jhyuklee** [comment]
Hi @Jasperty,

float to int conversion code is here:
https://github.com/uwnlp/denspi/blob/7762bfbc914346bb5ad933d44c6f8b95454cf62d/post.py#L574-L578

FYI, dequantization (int to float) is here:
https://github.com/uwnlp/denspi/blob/7762bfbc914346bb5ad933d44c6f8b95454cf62d/open/mips.py#L15-L16

Thank you.
